require 'rake/clean'

CLEAN.include %w[aux log blg bbl out nav sta toc vrb snm synctex.gz].map { |f| "**/*.#{f}" }
CLOBBER.include %w[./*.pdf]
TEX_FILES = Rake::FileList.new('**/*.tex')
STANDALONE = Rake::FileList.new('fig/*.tex')


desc 'Compile Presentation'
file 'presentation.pdf' => TEX_FILES do |tex|
  system('pdflatex presentation.tex')
  system('pdflatex presentation.tex')
end

STANDALONE.each do |f|
  base = File.basename(f, '.tex')
  desc "Build standalone figure for #{base}"
  file "#{base}.pdf" => f do |t|
    system("pdflatex #{t.prerequisites.first}")
  end
end
task :default => ['presentation.pdf']
