require 'rake/clean'

CLEAN.include %w[dvi aux log blg fls bbl fdb_latexmk out nav sta toc vrb snm synctex.gz].map { |f| "**/*.#{f}" }
CLOBBER.include '**/*.pdf'

TEX_FILES = Rake::FileList.new('**/*.tex')
STANDALONE = Rake::FileList.new('fig/*.tex')


desc 'Compile Presentation'
task :build do
  system('latexmk -pdf presentation.tex')
end

STANDALONE.each do |f|
  base = File.basename(f, '.tex')
  desc "Build standalone figure for #{base}"
  file "#{base}.pdf" => f do |t|
    system("latexmk -pdf #{t.prerequisites.first}")
  end
end

task :default => :build
