require 'rake/clean'

CLEAN.include %w[dvi aux log blg fls bbl fdb_latexmk out nav sta toc vrb snm synctex.gz].map { |f| "**/*.#{f}" }
CLOBBER.include '**/*.pdf'

desc 'Build Proposal Document'
task :build do
  system("latexmk -pdf proposal.tex")
end

task :default => :build
